# Generated by Django 2.0.5 on 2018-11-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jirani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('ID', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('estate', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('piecesRequested', models.CharField(max_length=20)),
            ],
        ),
    ]
