# Generated by Django 2.0.5 on 2018-11-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phoneNumber',
            field=models.CharField(max_length=255),
        ),
    ]
