# Generated by Django 2.0.5 on 2018-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_auto_20181110_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirani',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='jirani',
            name='piecesRequested',
        ),
        migrations.AddField(
            model_name='jirani',
            name='peopleApplied',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jirani',
            name='ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='county',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='estate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='landmark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='phoneNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirani',
            name='town',
            field=models.CharField(max_length=255),
        ),
    ]
