# Generated by Django 2.0.5 on 2018-11-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentCredentials',
            new_name='AgentCredential',
        ),
    ]
